################################################################################
# Influx Database for Time Series Metrics
################################################################################

influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - './influxdb/env.influxdb'
  volumes:
    - ./influxdb/data:/var/lib/influxdb

################################################################################
# Grafana Server for Visualizing the Metrics
################################################################################

grafana:
  image: grafana/grafana
  ports:
    - 3000:3000
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=secret
  links:
    - influxdb:influxdb
  volumes:
    - ./grafana/data:/var/lib/grafana

################################################################################
# Main SRE Demo Application / REST Service
################################################################################

sre-demo:
  image: znet/sre-demo
  ports:
    - 8080:8080
  links:
    - influxdb:influxdb

################################################################################
# Load Test Processor to Drive Traffic
################################################################################

load-test:
  image: znet/load-test
  links:
    - sre-demo:sre-demo
